services:
  lunabase:
    image: ghcr.io/utahrobotics/lunabotics/lunabase
    container_name: lunabase
    privileged: true
    tty: true
    pull_policy: always
    working_dir: /usr-ws-2023
    ports:
      - 10000:10000
    volumes:
      - type: bind
        source: ../
        target: /usr-ws-2023
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    environment:
      DISPLAY: "unix:0"
