services:
  lunabase:
    image: ghcr.io/utahrobotics/lunabotics/lunabase
    container_name: lunabase
    privileged: true
    tty: true
    pull_policy: always
    working_dir: /usr-ws-2023
    volumes:
      - type: bind
        source: ../
        target: /usr-ws-2023
    environment:
      DISPLAY: "unix:0"
