services:
  lunabase:
    image: ghcr.io/utahrobotics/lunabotics/lunabase
    container_name: lunabase
    privileged: true
    tty: true
    pull_policy: always
    ports:
      - "5901:5901"
      - "10000:10000"
    working_dir: /usr-ws-2023
    volumes:
      - type: bind
        source: ../
        target: /usr-ws-2023
