name: ColconTest

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - ".github/workflows/colcon_test.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    container: manglemix/usr_docker_repo:usr_base
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        shell: bash
        run: "apt-get update && source /opt/ros/foxy/setup.bash && rosdep update && rosdep install --from-paths src -y --ignore-src && colcon build --symlink-install"

      - name: Test
        shell: bash
        run: "source /opt/ros/foxy/setup.bash && colcon test --return-code-on-test-failure --event-handlers console_cohesion+"

